### ISSUE TITLE
macro_rules! definitions with parenthesis breaks filtering by item path

### ISSUE THREAD

**Issue by ElusiveMori** [dtolnay/cargo-expand#101]
Example:

```rust
// lib.rs
pub mod a;

// a.rs
macro_rules! b (
    () => {}
);
```

Running `cargo expand whatever` will dump the whole expanded crate.

If we change the macro to
```rust
macro_rules! b {
    () => {}
}
```

It will fail correctly with `WARNING: no such item: asdasda`

Having a macro like this anywhere in the crate will break the path resolution mechanism, for some reason, causing the path to be ignored all the time.

I'm not sure if macro_rules with parens has any rightful place to exist, but I just spent about half an hour trying to figure this one out ;-;

**Comment by ehuss** [comment]
This appears to be a bug in rustc's expander.  It emits the following:

```
#![feature(prelude_import)]
#[prelude_import]
use std::prelude::v1::*;
#[macro_use]
extern crate std;
pub mod a {
    macro_rules! b(() => { })
}
```

Notice that it strips the semicolon.

**Comment by ehuss** [comment]
Posted https://github.com/rust-lang/rust/pull/81888 with a fix.

**Comment by dtolnay** [comment]
Confirmed fixed as of nightly-2021-02-10 by https://github.com/rust-lang/rust/pull/81888.
