### ISSUE TITLE
Default theme unreadable on a white-background terminal

### ISSUE THREAD

**Issue by glandium** [dtolnay/cargo-expand#107]
The default theme seems to be using an explicit white color for normal text, which doesn't play well with non-black-background terminal windows.
![Screenshot from 2021-03-30 08-43-38](https://user-images.githubusercontent.com/1038527/112913300-56788d00-9134-11eb-9328-c6ebb64b9571.png)

The ansi theme, however, doesn't seem to be using explicit colors for normal text, and is readable with both white-background and black-background.
![Screenshot from 2021-03-30 08-44-23](https://user-images.githubusercontent.com/1038527/112913394-7a3bd300-9134-11eb-831b-3c254ff3ee2c.png)
![Screenshot from 2021-03-30 08-44-48](https://user-images.githubusercontent.com/1038527/112913404-7e67f080-9134-11eb-9166-48efb2456e74.png)

**Comment by dtolnay** [comment]
We don't have a default theme as far as I know. It's just whatever `bat` does. I think this relates to https://github.com/sharkdp/bat#highlighting-theme:

> `bat` looks good on a dark background by default. However, if your terminal uses a light background, some themes like `GitHub` or `OneHalfLight` will work better for you.

**Comment by SuperFluffy** [comment]
If someone else was confused because they thought `cargo expand` falls back to bat's settings: **`cargo-expand` does not pick up bat's settings**. That is, if you want to have `cargo-expand` match this bat theme:

```
# $XDG_CONFIG_HOME/bat/config
--theme="Solarized (light)"
```

Then you need to set the following for `cargo-expand`:

```
# $XDG_CONFIG_HOME/bat/config
theme = "Solarized (light)"
```

**Comment by vi** [comment]
`~/.cargo/bat/config` is `theme = "Solarized (light)"`, but `cargo expand` still renders white text on white background.

Also how do I pipe the output to `less -R` without losing the colours?

**Comment by albel727** [comment]
The theme works for me after adding the following to the `~/.cargo/config` file (*not* `~/.cargo/bat/config`):
```toml
[expand]
theme="Solarized (light)"
```
