### ISSUE TITLE
Cargo expand fails to format code with documentation comments

### ISSUE THREAD

**Issue by Robbepop** [dtolnay/cargo-expand#111]
I encountered a problem with documentation comments in Rust code that cause `cargo expand` to have unformatted blobs of code in its output.
![2021-06-14-132407_1436x644_scrot](https://user-images.githubusercontent.com/8193155/121891566-e5507b00-cd1b-11eb-9d8f-1e91a8640cb1.png)

In the picture above you can clearly see the entirely unformatted section of code next to some properly fomatted sections of code.
The whole things got fixed by manually converting some `///` doc comments into normal comments `//` basically removing them.

I don't yet know whether this also happens with other attributes, however, note that the code does contain other attributes should as `#[inline]` or certain derives which got expanded properly.

Also note that `cargo expand` in fact seems to use `rustfmt` since `cargo expand --ugly` produces very different output that does not contain these entirely unformatted sections of code. However, code with `cargo expand --ugly` tends to look more ... ugly in general so it is also not a serious work around for me for now.

You can reproduce the problem with:
```rust
const _: () = {
    /// Breaks cargo-expand's formatting
    struct A;
};
```
This issue seems to be similar to https://github.com/dtolnay/cargo-expand/issues/71.

**Comment by dtolnay** [comment]
I would be shocked if this were a cargo-expand issue. Could you report to rustfmt instead, with a minimized repro? Cargo-expand does not control what parts of the file rustfmt would run on.

**Comment by Robbepop** [comment]
@dtolnay The following minimal code snippet can be reproduced with `cargo-expand` tool but not with `rustfmt` tool.
```rust
const _: () = {
    /// Breaks cargo-expand's formatting
    struct A;
};
```
What do you think this could be the reason for this? I opened an issue for the `rustfmt` tool and the problem is that this code snippet really only works for reproducability with `cargo-expand` but not `rustfmt`.
