### ISSUE TITLE
Feature request: format long code

### ISSUE THREAD

**Issue by soerenmeier** [dtolnay/cargo-expand#112]
While expanding some code which uses `tokio::select` it seemed like no formatting happened. After posting an issue https://github.com/rust-lang/rustfmt/issues/4878 on rustfmt the answer was that it worked as intended.

I'm proposing to add an argument like `--fmt-long` or something like that, that performs two formatting passes. One with a long max-width and another with the default one.

If that's a feature you would add, I'd be willing to make a PR.

**Comment by dtolnay** [comment]
I would prefer not to make a change here. This is squarely territory that a formatter should handle. I would be interested in someone making a formatter that is better than rustfmt, and I would be open to supporting that in cargo-expand. As long as it can be invoked as `$formatter --edition=2018 path/to/input.rs` it would even work without any code change in cargo-expand, by setting a RUSTFMT environment variable to point to it.

https://github.com/dtolnay/cargo-expand/blob/10002dfe11f9dd83b34b59078e41733a3bebdde4/src/main.rs#L267
