### ISSUE TITLE
error[E0599]: no method named `add_from_folder` found for struct `ThemeSet` in the current scope

### ISSUE THREAD

**Issue by piavgh** [dtolnay/cargo-expand#122]
Hi @dtolnay ,

I tried to install cargo-expand on my computer but I got this issue

<img width="932" alt="Screen Shot 2021-12-26 at 10 21 51 PM" src="https://user-images.githubusercontent.com/4060207/147412560-79903383-727c-42fa-adb4-0fc3354bbf1f.png">

```
error[E0599]: no method named `add_from_folder` found for struct `ThemeSet` in the current scope
```

Do you know how to fix this? Thanks

This is my environment:
- Mac OS Monterey 12.1
- rustup 1.24.3 (ce5817a94 2021-05-31)
- rustc 1.59.0-nightly (51e8031e1 2021-12-25)

**Comment by taiki-e** [comment]
I think this is the same issue as https://github.com/sharkdp/bat/issues/1991, and can be worked around by installing using the `--locked` flag.

**Comment by dtolnay** [comment]
Closing in favor of https://github.com/trishume/syntect/issues/402.

**Comment by piavgh** [comment]
Thank you guys. I use `cargo install --locked cargo-expand` and it works
