### ISSUE TITLE
memory allocation of 7881122326526296064 bytes failed

### ISSUE THREAD

**Issue by mattfbacon** [dtolnay/cargo-expand#127]
When I try to use `cargo expand` I get this output:

```
$ cargo +nightly expand
    Checking crate-name v0.1.0 (/path/to/crate)
    Finished dev [unoptimized + debuginfo] target(s) in 0.23s

memory allocation of 7881122326526296064 bytes failed
fish: Job 1, 'cargo +nightly expand' terminated by signal SIGABRT (Abort)
```

I'm not sure I can give much more information.

**Comment by ehuss** [comment]
Can you share:
* Version of nightly (try the latest if possible)
* Version of cargo-expand
* Which platform (x86_64-unknown-linux-gnu? x86_64-apple-darwin?)

If you'd be willing to debug it, I might suggest using gdb or lldb to see where the allocation is being made.

**Comment by dtolnay** [comment]
This is a regression in the syntect crate &mdash; https://github.com/trishume/syntect/issues/412. It should work again if you reinstall with `cargo install cargo-expand --force` because a workaround was published a couple days ago.
