### ISSUE TITLE
Cargo-expand tries to use beta toolchain of cargo

### ISSUE THREAD

**Issue by Venryx** [dtolnay/cargo-expand#135]
I'm noticing that in some cases, `cargo expand` is executing the following command: (as seen using Process Hacker 2)
```
"\\?\C:\Users\Stephen\.rustup\toolchains\beta-x86_64-pc-windows-msvc\bin\cargo.exe" rustc --profile=check --color never -- -o C:\Users\Stephen\AppData\Local\Temp\cargo-expandUUE54z\expanded -Zunpretty=expanded
```

This command then fails with the error:
```
error: the option `Z` is only accepted on the nightly compiler
error: could not compile `app-server-rs`
```

The issue would seem to be that `cargo expand` is using the beta-toolchain of cargo, rather than the nightly version that I have installed here: `C:\Users\Stephen\.rustup\toolchains\nightly-2021-01-24-x86_64-pc-windows-msvc`

Interestingly, I had `cargo expand` working fine earlier today, so I must have done something to confuse it. Creating this issue so others hitting the same issue can find the solution. (once I find it myself, haha)

**Comment by Venryx** [comment]
Okay, the issue seems to have been that while I had the `nightly` folders above, they for some reason are not detected when `cargo +nightly --version` is run, which makes cargo-expand think that no nightly toolchain exists, as seen here: https://github.com/dtolnay/cargo-expand/blob/007a44549f7ad5ddab16baf6fdd5810896579797/src/main.rs#L107-L113

When cargo-expand thinks there is no nightly version installed, it falls back to just using whatever version is cargo is set as the default -- which in my case was the beta version. (which does not support `-Z` options, and thus fails)

The fix was to run `rustup install nightly`, which created the folder `C:\Users\Stephen\.rustup\toolchains\nightly-x86_64-pc-windows-msvc`, which is correctly detected by `cargo +nightly --version`, meaning cargo-check knows about it and makes use of it.

Leaving the issue open for now, as it seems there should be some sort of warning when this situation comes up. (eg. a message in the console saying, `No nightly version was detected, which is required for cargo-expand to function. Have you run "rustup install nightly"?`)

**Comment by dtolnay** [comment]
I think this behavior is fine.

Locally built toolchains (i.e. "dev mode" rustc) is not nightly but still supports `-Zunpretty=expanded`, so I don't think failing out or printing warnings would be better. It's not possible in general to tell whether a toolchain does or does not support Z flags without just running it.
