### ISSUE TITLE
Add support of 2021 rust edition

### ISSUE THREAD

**Issue by cyphersnake** [dtolnay/cargo-expand#137]
```rust
error: failed to parse manifest at `/home/*/projects/sandbox/Cargo.toml`
Caused by:
  feature `edition2021` is required
  consider adding `cargo-features = ["edition2021"]` to the manifest
```
at project with Cargo.toml
```toml
[package]
name = "sandbox"
version = "0.1.0"
edition = "2021"

[dependencies]
```
and empty lib.rs

Adding a feature does not help, since it should be not only in crates of workspace, but in in all dependencies wiith 2021 edition

**Comment by ehuss** [comment]
I suspect you likely have an old version of nightly installed.  Can you say which version you have?

**Comment by cyphersnake** [comment]
Yes, you are right, running via `rustup run` helped.
