### ISSUE TITLE
Expanding integration tests

### ISSUE THREAD

**Issue by bicarlsen** [dtolnay/cargo-expand#139]
When running `cargo expand --lib --tests` integration tests (located in the `tests` folder) are not epanded. I have confirmed the the same tests as unit tests (located in `src/lib.rs`) are expanded properly.

Is there a way to include the integration tests in the expansion?

**Comment by ehuss** [comment]
`cargo expand` can only expand one target at a time. You have to pass the name of the integration test as in `cargo expand --test foo`.

**Comment by bicarlsen** [comment]
That results in the error `no test target named '<test_name>'`.

Do I have to qualify the test in some way? e.g. `cargo expand --test my_integration_tests::test_name`?

**Comment by bicarlsen** [comment]
I also tried specifiying the test target in my `Cargo.toml` as described in [Issue #40] (https://github.com/dtolnay/cargo-expand/issues/40#issuecomment-456214949) but it did not resolve the issue.

**Comment by dtolnay** [comment]
Sounds like you're putting the name of the function, not the name of the integration test target.

It's `cargo expand --test my_integration_tests`.

**Comment by bicarlsen** [comment]
Ah, yes that was the issue. Thank you for the clarification.
