### ISSUE TITLE
I could not run `cargo expand` while I on the nightly rust env

### ISSUE THREAD

**Issue by emadbaqeri** [dtolnay/cargo-expand#149]
Hey there, I'm trying to run `cargo expand` on one of my projects, the problem is it is blaming that the compiler needs to be the nightly version. 
This is the error:
```bash
error: the option `Z` is only accepted on the nightly compiler
error: could not compile `dummy_project`
```
This is the output of `rustup show`:

```bash
Default host: aarch64-apple-darwin
rustup home:  /Users/emad/.rustup

installed toolchains
--------------------

stable-aarch64-apple-darwin
nightly-aarch64-apple-darwin (default)

active toolchain
----------------

nightly-aarch64-apple-darwin (default)
rustc 1.63.0-nightly (1f34da9ec 2022-06-14)
```
Any idea on this?

**Comment by dtolnay** [comment]
I can't look into this, but if you track this down and figure out a code fix or documentation fix, I would be happy to accept it.

**Comment by emadbaqeri** [comment]
Hey @dtolnay, I will take look into it in my down time

**Comment by OctoRocket** [comment]
I am also having this issue

**Comment by lanahuong** [comment]
Hey, I also encountered this issue, here is how I solved it if it can help
I had installed rust via the rust package from the arch extra repo. Deleting it and installing rustup with the script from https://rustup.rs/ fixed the problem.
I remember other issues with the rust package on my first install, better use the rustup install script
