### ISSUE TITLE
[BUG] Can't use with rustfmt installed not by rustup

### ISSUE THREAD

**Issue by CoelacanthusHex** [dtolnay/cargo-expand#158]
After https://github.com/dtolnay/cargo-expand/pull/45, cargo-expand only checks rustfmt installed by rustup.
But many people, install rustfmt from the distro package manager, such as the `rust` package of Arch (include rustfmt).
In this case, cargo can't find rustfmt, then aborted and told user they must install rustfmt with rustup.
It's a REALLY REALLY TERRIBLE idea because it restricts users' freedom to choose their own tool installation method. 
Hopefully, you can seriously consider whether you must use rustup.

**Comment by dtolnay** [comment]
I think the implementation in this crate is fine.

If someone is interested in the toolchain_find crate supporting non-rustup environments, that should be made as a PR to the toolchain_find crate.
