### ISSUE TITLE
Can cargo-expand only expand procedural-macro, not including declarative macros?

### ISSUE THREAD

**Issue by StevenJiang1110** [dtolnay/cargo-expand#167]
I want to define and export declarative macros inside procedural-macro. For debug use, I want to see the exact declarative macros. Below is a simple example.
```rust
#[proc_macro]
pub fn example_macro(input: proc_macro::TokenStream) -> proc_macro::TokenStream {
    quote!(
        #[macro_export]
        macro_rules! print_hello {
            () => (
                println!("hello world");
            )
        }
    ).into()
}
```

I only want to expand `example_macro`, but not `print_hello` inside, is this possible? Thanks a lot.

**Comment by dtolnay** [comment]
It isn't. I would prefer not to support this in this crate, but anyone else would be free to implement it in a different tool!
