### ISSUE TITLE
Is there a way to only expand an associated function on a type?

### ISSUE THREAD

**Issue by cyqsimon** [dtolnay/cargo-expand#168]
```rust
struct MyType {
    foo: usize,
}
impl MyType {
    fn print_foo(&self) {
        println!("{}", self.foo);
    }
}
```

Currently it seems like the only way to expand `MyType::print_foo` is to expand the entire module, or at least I haven't found a way to accomplish this. Is there a particular syntax for this that I'm missing?

If not, please see this as a feature request. Much thanks. =)

**Comment by dtolnay** [comment]
The item selection is handled by https://github.com/TedDriggs/syn-select. Could you please file this feature request over there?

@TedDriggs
