### ISSUE TITLE
Macro expansion problem

### ISSUE THREAD

**Issue by Vzz1c** [dtolnay/cargo-expand#173]
let x = String::from("Hello!");
    println!("{}", x);
----------------------------------
    let x = String::from("Hello!");
    {
        ::std::io::_print(format_args!("{0}\n", x));
    };
---------------------------------
After expanding there is still a macro =>format_args!
, you can't see the actual expanded code

**Comment by dtolnay** [comment]
This is working correctly. `format_args` does not expand to Rust code.

**Comment by hh9527** [comment]
@dtolnay 
Is there any more detail information/reason about special point of `format_args`?
I am thinking about something like idea of `rust2c`, and want to use `cargo expand` to expand all macros as a start point of transforming.

**Comment by dtolnay** [comment]
See https://github.com/rust-lang/rust/issues/99012.

**Comment by gemesa** [comment]
You can do this instead:

```
$ cargo rustc -- --emit asm -Z unpretty=hir                                    
   Compiling rust-lab v0.1.0 (/home/gemesa/git-repos/rust-lab)
#[prelude_import]
use std::prelude::rust_2024::*;
#[macro_use]
extern crate std;
fn main() {
    { ::std::io::_print(format_arguments::new_const(&["Hello, world!\n"])); };
}
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.05s
```

**Comment by superobertking** [comment]
> You can do this instead:
> 
> ```
> $ cargo rustc -- -Z unpretty=hir 
>    Compiling rust-lab v0.1.0 (/home/gemesa/git-repos/rust-lab)
> #[prelude_import]
> use std::prelude::rust_2024::*;
> #[macro_use]
> extern crate std;
> fn main() {
>     { ::std::io::_print(format_arguments::new_const(&["Hello, world!\n"])); };
> }
>     Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.05s
> ```

This is helpful! Thank you!
