### ISSUE TITLE
Feature Request : output sources to folder

### ISSUE THREAD

**Issue by benze** [dtolnay/cargo-expand#174]
I'm just starting up in Rust and like the idea of being able to "see" what macros create.

I think a beautiful feature for cargo expand would be to be able to identify and output folder where each file is dumped analogous to the source tree.  It would make for much easier reading than having to pipe the entire output of `cargo expand` into a giant file and read through the whole file.

Would the feature allow for something like that?

Ex: `cargo expand --lib --output-dir target/expand` or something along those lines

**Comment by dtolnay** [comment]
I would prefer not to support this in this project, but anyone else should feel free to implement this as a different tool.
