### ISSUE TITLE
serde_derive breaks module path

### ISSUE THREAD

**Issue by figsoda** [dtolnay/cargo-expand#177]
serde_derive emits `macro_rules! try`, which doesn't parse with syn v2

minimum reproducible example
```rust
// src/lib.rs
#[derive(serde::Deserialize)]
struct A;

pub fn a() {}
```

```bash
cargo expand a
```

expected: `pub fn a() {}`

actual: everything gets printed because `syn::parse_file` fails here
https://github.com/dtolnay/cargo-expand/blob/a1f18dbc0886db5ac82ec5d6e1935480d05aa29e/src/main.rs#L211

**Comment by dtolnay** [comment]
Fixed in cargo-expand 1.0.42.
