### ISSUE TITLE
Would it make sense to offer an `--hygiene` switch to run `-Zunpretty=expanded,hygiene` internally?

### ISSUE THREAD

**Issue by bluenote10** [dtolnay/cargo-expand#188]
Following the link in [the disclaimer on macro hygiene](https://github.com/dtolnay/cargo-expand#disclaimer) leads to a [section in the book](https://doc.rust-lang.org/1.30.0/book/first-edition/macros.html#debugging-macro-code) that mentions that it is possible to get debug information on what is happening under the hood in terms of macro hygiene. The book mentions to use `--pretty expanded,hygiene` instead of `--pretty expanded` to accomplish that. For some reason this switch didn't work for me, but `cargo +nightly rustc -- -Zunpretty=expanded,hygiene` did. The expanded code then contains information in the form of comments that allows to identify the symbol instance, which is quite handy if a recursive macro uses the same variable name (like `temp`) repeatedly.

Since `cargo expand` is basically a wrapper around `cargo rustc --profile=check -- -Zunpretty=expanded`, I wondering if it would be easy to just add a `--hygiene` switch that forwards the `hygiene` argument to the `-Zunpretty` value?

**Comment by dtolnay** [comment]
I would prefer not to build this into this crate.
