### ISSUE TITLE
Syntax highlight

### ISSUE THREAD

**Issue by Yamakaky** [dtolnay/cargo-expand#2]
You could pipe the output through a terminal syntax highlighter, like [highlight](http://www.andre-simon.de/doku/highlight/en/highlight.php) or [pygmentize](http://pygments.org/).

**Comment by dtolnay** [comment]
Fixed in 2daf1ccc44c43eb34234a29d94aee1f3620ff82b to use `pygmentize`.

**Comment by Yamakaky** [comment]
Yeay!
