### ISSUE TITLE
Expand test modules

### ISSUE THREAD

**Issue by gnzlbg** [dtolnay/cargo-expand#20]
I am trying to expand some macros inside `#[cfg(test)] mod tests { .... }` modules and failing. 

I have tried: `cargo expand --tests`, `cargo expand --test path/to/file.rs`, `cargo expand --test `file`, `cargo expand test` (like cargo test but with expand), without any luck. 

I've also tried by copying the relevant code into `tests/file.rs` and trying to `cargo expand --test tests/file.rs` instead.

**Comment by dtolnay** [comment]
Expanding test code in the library requires passing `--test` to rustc (not to cargo). This should work: `cargo expand -- --test`.

**Comment by gnzlbg** [comment]
Thanks, I managed to get it to work. I was doing `cargo expand -h` which was suggesting to use  `--test`. It was very confusing.
