### ISSUE TITLE
Use cargo expand as a library

### ISSUE THREAD

**Issue by fzyzcjy** [dtolnay/cargo-expand#202]
Hi thanks for the library! When developing https://github.com/fzyzcjy/flutter_rust_bridge, I find it great if cargo-expand could be used as a Rust function, such that there is no need to separately install a binary, etc.

**Comment by dtolnay** [comment]
I would prefer not to build a Rust API into this crate, but someone else should feel free to maintain a library for this.

**Comment by fzyzcjy** [comment]
Thanks for the reply
