### ISSUE TITLE
Showing expanded code of examples

### ISSUE THREAD

**Issue by LukasKalbertodt** [dtolnay/cargo-expand#22]
I just tried `cargo expand --example foobar` but it didn't show any output... How difficult would it be to add this feature?

**Comment by dtolnay** [comment]
Thanks for reporting this! I tried the following, but I do see output.

```
git clone https://github.com/LukasKalbertodt/stable-vec
cd stable-vec
cargo expand --example compact
```

I am using rustc 1.24.0-nightly (7eb64b86c 2017-12-20) on x86_64-unknown-linux-gnu target and cargo-expand 0.3.12. Can you tell what about your setup may be different?

**Comment by LukasKalbertodt** [comment]
Wow, thanks for the quick reply!

I only tested it with [`mauzi`](https://github.com/LukasKalbertodt/mauzi). That crate is using the new `proc_macro` stuff; maybe that's why it's not working. Checking out that repository and executing this:

```
$ cargo expand --example full
   Compiling mauzi v0.0.2 (file:///home/lukas/dev/mauzi)
    Finished dev [unoptimized + debuginfo] target(s) in 0.12 secs
```

... no output. Or am I doing something wrong? ^_^

**Comment by dtolnay** [comment]
I see output for mauzi as well. https://paste.rs/CNQ

Do you see it for stable-vec but not mauzi? What is `rustc --version`?

**Comment by LukasKalbertodt** [comment]
*Very* strange. It works for me now as well. I am not sure if this is worth debugging. So basically, I executed these commands first (lines starting with `[...` are by me, everything else is the original output):

```
mauzi (master)$ rustc -V
rustc 1.24.0-nightly (7eb64b86c 2017-12-20)
mauzi (master)$ cargo install cargo-expand
[... installing]
mauzi (master)$ cargo expand
   Compiling mauzi v0.0.2 (file:///home/lukas/dev/mauzi)
    Finished dev [unoptimized + debuginfo] target(s) in 0.11 secs
[... works, prints out the expanded lib form]

mauzi (master)$ cargo expand --example full
   Compiling mauzi v0.0.2 (file:///home/lukas/dev/mauzi)
    Finished dev [unoptimized + debuginfo] target(s) in 0.12 secs

mauzi (master)$ cargo rustc --example full -- -Z unstable-options --pretty=expanded
[... works perfectly]
```

(this is when I reported the issue)

Then I did a lot of rustup cleanup (removing unneeded targets and so on and finally I did a `rustup update` (which, however, did not update nightly, as you will see below).

And now, `cargo expand --example full` works fine. And I still have `rustc 1.24.0-nightly (7eb64b86c 2017-12-20)` installed. I'm confused.

But I guess, this is really not worth debugging. It works now after all. Sorry for this rather useless issue :P

**Comment by dtolnay** [comment]
Strange. Let's close the issue but follow up if this keeps happening or you find a way to reproduce it.
