### ISSUE TITLE
No error when rustfmt fails

### ISSUE THREAD

**Issue by adwhit** [dtolnay/cargo-expand#23]
...at least, I think that's the problem.

When running `cargo expand` on a fairly complex codebase with lots of derives, it does... nothing. That is, it compiles the crate, reports "Finished", then exits (and returns no error). 

Manually dumping the expanded code and prettifying, like so:
```
cargo rustc -- --pretty=expanded -Z unstable-options > expanded.rs
rustfmt expanded.rs
```
I find that due to some mismatch between `syn` and `libsyntax` or something, `rustfmt` is failing (on valid code) with some parse error, but the error is being swallowed by `cargo-expand`.

Similarly if I try to run with some dummy test, I get some evidence that `cargo-expand` is trying to cat a non-existent directory.
```
cargo expand --test whatever  
error: no test target named `whatever`
cat: /tmp/cargo-expand.1MhZhIEnZTqi/expanded: No such file or directory
```

It would be nice if `cargo-expand` recognized and handled these failures gracefully.

Versions: 
cargo-expand v0.3.12
cargo 0.26.0-nightly (6a8eb71f6 2018-01-13)
rustc 1.25.0-nightly (4e3901d35 2018-01-23)
rustfmt-nightly v0.3.6

**Comment by dtolnay** [comment]
Fixed in #27.
