### ISSUE TITLE
`cargo expand` fails if the build script uses the new format for outputs

### ISSUE THREAD

**Issue by maia-s** [dtolnay/cargo-expand#232]
For example, if the build script outputs a feature like this:
```rust
println!("cargo::rust-cfg=feature=some-feature");
```

`cargo expand` fails with
```
error: invalid output in build script of `(crate)`: `cargo::rust-cfg=feature=some-feature`
Unknown key: `rust-cfg`.
```

It works if I replace the two colons in the println with a single colon, but two colons is the documented syntax now.

```
% cargo expand --version
cargo-expand 1.0.90
```

**Comment by ehuss** [comment]
I believe the error is correct. It looks like you have a typo. It should be `rustc-cfg` with a `c`.

**Comment by maia-s** [comment]
Oh, you're correct! I wonder why cargo didn't warn me about that. I'll close this.
