### ISSUE TITLE
Can something be done about the bloat?

### ISSUE THREAD

**Issue by grothesque** [dtolnay/cargo-expand#233]
The documentation says that this crate is a wrapper around the cargo command `cargo rustc --profile=check -- -Zunpretty=expanded`.

I installed it in the recommended way.  This downloaded over 100 dependencies and took more than 2 minutes to compile (on my old laptop).  Sure, today we have plenty of clock cycles and disk space to spare, but isn't there perhaps a way to un-bloat this "simple wrapper" a bit without loosing core functionality?

Also, the resulting executable takes 9 MB on disk.  This is bigger than the CPython executable.  I know that rustc-created executables are big by default, but have a look here: https://www.reddit.com/r/rust/comments/cg3p5m/cargobloat_08_debloated_5x_smaller_10x_faster/

Cheers from someone who learned programming on a Sinclair ZX Spectrum with 48 K of RAM.  (It already had a C compiler.)

**Comment by dtolnay** [comment]
It is not something I intend to work on, but if you want to send PRs then I can evaluate whatever tradeoffs they make.

I would expect that most of the size is from `bat` which bakes in syntax highlighting assets for various grammars.
