### ISSUE TITLE
Force color output on for pygmentize if `--color=always` is passed

### ISSUE THREAD

**Issue by luser** [dtolnay/cargo-expand#34]
Thanks for the useful tool! I found myself piping the output to `less`, but there doesn't seem to be a way to ask the tool to produce colorized output from pygmentize if stdout is not a tty. That would be helpful!

**Comment by dtolnay** [comment]
Seems reasonable! I would accept a PR for this.

**Comment by dtolnay** [comment]
Fixed in cargo-expand 0.4.0. Tested with:

```bash
cargo expand --color=always | less -r
```
