### ISSUE TITLE
Use `which` crate for locating tools

### ISSUE THREAD

**Issue by luser** [dtolnay/cargo-expand#35]
I contributed a bunch of code to the [`which`](crates.io/crates/which) crate a while back to use in sccache. I was looking at the code here and it seems like you could probably use that to replace some of the custom `which` impl you have.

**Comment by dtolnay** [comment]
Looks good. I would accept a PR to use the `which` crate.

**Comment by dtolnay** [comment]
I switched to the [toolchain_find](https://github.com/gsquire/toolchain_find) crate which supports our use case better.
