### ISSUE TITLE
Proposal: Expand whole project source to the ad hoc project  

### ISSUE THREAD

**Issue by cheblin** [dtolnay/cargo-expand#37]
Expand (**with preserved comments (?)**) whole project source files, and copy, other project related files, to the other project, 
So obtained project copy, will contain "pure" source and can be run and debugged as is, without any expansion.

Can be added option - how deep to expand macros. Only located in user code... located in user code and used crates...

**Comment by dtolnay** [comment]
Thanks! This proposal sounds substantially different from what cargo-expand currently does, so I would prefer to see this use case addressed in a different crate.

The second part, control over how deeply macros are expanded, is tracked in #11.
