### ISSUE TITLE
Switch to using syn-select

### ISSUE THREAD

**Issue by TedDriggs** [dtolnay/cargo-expand#46]
dtolnay/request-for-implementation#1 asked for a crate to handle syntactic filtering by path in a single file. [syn-select](https://crates.io/crates/syn-select) is now available, matching the test cases specified in the original ticket.

**Comment by dtolnay** [comment]
Thanks, looks great. I opened #47 to pick up your crate.

One thing I noticed is that the path parse errors used to be somewhat better. Before:

```console
$ cargo expand a::x,
error: Invalid value for '<ITEM>': `x,` is not an identifier
```

After:

```console
$ cargo expand a::x,
error: Invalid value for '<ITEM>': Invalid path
```

Would it be possible to include more information in the errors about what made the path invalid?

**Comment by TedDriggs** [comment]
Yes, that's easy to do.

**Comment by TedDriggs** [comment]
0.1.2 is published, including the better error message.

**Comment by dtolnay** [comment]
The error message is pretty much the same in 0.1.2. Is this the intended fix?

```console
$ cargo expand a::x,
error: Invalid value for '<ITEM>': Invalid path segment
```

**Comment by TedDriggs** [comment]
No... What are you calling? I changed the fmt::Display implementation, but not description().
