### ISSUE TITLE
Consider setting time limit on rustfmt

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/cargo-expand#51]
Rustfmt can hit cases where code takes exponentially long to format, particularly in macro-generated code. https://github.com/rust-lang/rustfmt/issues/3465

We may want to consider limiting rustfmt execution time to some small number of seconds, after which we kill the rustfmt process and fall back to unformatted code.

**Comment by gsquire** [comment]
Is there a way to supply a timeout to a `Command`? If not I thought you could leverage the `select!` macro in [crossbeam-channel](https://docs.rs/crossbeam-channel/0.3.8/crossbeam_channel/#selection) with a timer as the default case. It may get tricky with threads and calling `kill` on the child process if it takes too long but it may be an option.

**Comment by dtolnay** [comment]
Fixed by using https://github.com/dtolnay/prettyplease instead of rustfmt.
