### ISSUE TITLE
Issue when expanding then testing

### ISSUE THREAD

**Issue by Freyskeyd** [dtolnay/cargo-expand#66]
Hello,

I'm trying to debug a proc_macro and I'm using the expand -> tests methods to debug the generated code.

I came across an issue here it is:

I've a simple tests file:

```rust
#[test]
fn add_one() {
	assert!(true);
}
```

which generate an expand of:

```rust
#![feature(prelude_import)]
#![no_std]
#[prelude_import]
use ::std::prelude::v1::*;
#[macro_use]
extern crate std as std;
extern crate test as test;
#[cfg(test)]
#[rustc_test_marker]
pub const add_one: test::TestDescAndFn = test::TestDescAndFn {
    desc: test::TestDesc {
        name: test::StaticTestName("add_one"),
        ignore: false,
        allow_fail: false,
        should_panic: test::ShouldPanic::No,
    },
    testfn: test::StaticTestFn(|| test::assert_test_result(add_one())),
};
fn add_one() {
    if !true {
        {
            ::std::rt::begin_panic("assertion failed: true", &("tests/simple.rs", 3u32, 5u32))
        }
    };
}
pub mod __test_reexports {
    pub use super::add_one;
}
#[main]
pub fn main() -> () {
    extern crate test;
    test::test_main_static(&[&__test_reexports::add_one])
}

```

After adding some missing `#[features(test, libstd_sys_internals, rustc_attrs)]`

I try to run tests and get this error:

```rust
error[E0618]: expected function, found `test::TestDescAndFn`
  --> tests/simple-expand.rs:18:60
   |
11 | / pub const add_one: test::TestDescAndFn = test::TestDescAndFn {
12 | |     desc: test::TestDesc {
13 | |         name: test::StaticTestName("add_one"),
14 | |         ignore: false,
...  |
18 | |     testfn: test::StaticTestFn(|| test::assert_test_result(add_one())),
   | |                                                            ^^^^^^^--
   | |                                                            |
   | |                                                            call expression requires function
19 | | };
   | |__- `test::TestDescAndFn` defined here
```

Both the const and the function have the same name and it seems to be a conflict.
By renaming the function everything work as expected.

Am I doing something wrong or is it a limitation of how I tests ? :x

**Comment by dtolnay** [comment]
This is the intended behavior -- the result of expanding macros is not intended to be compilable code. The compiler's representation of source code is more expressive than text so the conversion to text necessarily has to be lossy. See the disclaimer in https://github.com/dtolnay/cargo-expand#disclaimer.

**Comment by Freyskeyd** [comment]
thank's for the quick answer.

Their is no other way to debug proc_macro_derive ?
I didn't find a suitable one other than expanding, updating and testing.

**Comment by dtolnay** [comment]
An approach that usually works well is handwriting the code you want to generate, getting that compiling, and only then starting on the macro code to generate the same thing as output. Starting with macro code before you have a compilable handwritten impl is less productive.

**Comment by Freyskeyd** [comment]
Hello, 

Thank's for helping me on this issue. I will close it.
