### ISSUE TITLE
README's link to Rust Book's Macro Hygiene section outdated

### ISSUE THREAD

**Issue by Y0hy0h** [dtolnay/cargo-expand#70]
The [last link in the README](https://github.com/dtolnay/cargo-expand/blame/master/README.md#L161) that points to a section on macro hygiene refers to the first edition of the Rust book. Unfortunately, the newest edition doesn't appear to have a section for macro hygiene (the search feature doesn't give hits for "hygiene"). It only has an [appendix dedicated to macros](https://doc.rust-lang.org/1.30.0/book/2018-edition/appendix-04-macros.html).

I'm unsure how to fix the link in the README, therefore I'm opening this issue instead of a PR. It looks like the link was supposed to provide insight into the limitations of cargo-expand. Is there an up-to-date replacement for the link?

**Comment by ehuss** [comment]
I think it would be fine to link to https://doc.rust-lang.org/1.30.0/book/first-edition/macros.html#hygiene.

**Comment by dtolnay** [comment]
Thanks!
