### ISSUE TITLE
Is it possible to use a pure rust lib rather than onig? 

### ISSUE THREAD

**Issue by gilescope** [dtolnay/cargo-expand#74]
Is it possible to use a pure rust lib rather than onig? I'm mostly asking this question so that the answer is documented. When it's not pure rust people can have trouble compiling with gcc on windows on gnu toolchain - it requires more setup and configuration of a windows machine than just installing rustup.

As I said I'm sure there's some good reasons behind using onig versus depending on some parts of ripgrep, just would be nice to know so that I can stop wondering.... :-)

**Comment by dtolnay** [comment]
This crate doesn't use onig, it is pulled in through syntect. I am sad about it too. https://github.com/trishume/syntect/issues/12

**Comment by gilescope** [comment]
Seems like soonish there might be a fancy-regex feature: https://github.com/trishume/syntect/pull/270

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by trishume** [comment]
The `fancy-regex` mode was just merged and released as [v4.0.0](https://github.com/trishume/syntect/pull/270)! You may want to try using it to fix this issue, although it does halve performance so you may only want to use it on platforms where it's needed.

Still hoping that onig's build will eventually improve but for now `fancy-regex` is a good option.

**Comment by gilescope** [comment]
Even as a feature that’s helpful. Ideally a bit of the readme can just say for the max-rust version do ‘X’.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by trishume** [comment]
I've already added such a section to the Readme :)

**Comment by gilescope** [comment]
Thanks - I was thinking of the readme for cargo-expand as that’s where people will look for it initially.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dtolnay** [comment]
Fixed in 0.5.0.

**Comment by gilescope** [comment]
Beautiful, thanks to everyone involved!
