### ISSUE TITLE
Bug ? panicked at 'assertion failed: `(left == right)`

### ISSUE THREAD

**Issue by JRAndreassen** [dtolnay/cargo-expand#86]
cargo expand --lib >generated.rs
    Checking moah_client v0.1.0 (C:\Development\Rust\PRTGC-Sensors\moah_client)
thread 'rustc' panicked at 'assertion failed: `(left == right)`
  left: `23`,
 right: `1`', src\librustc_ast_pretty\pprust.rs:441:17
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: <std::io::IoSliceMut as core::fmt::Debug>::fmt
   3: std::panicking::take_hook
   4: std::panicking::take_hook
   5: rustc_driver::report_ice
   6: std::panicking::rust_panic_with_hook
   7: rust_begin_unwind
   8: std::panicking::begin_panic_fmt
   9: rustc_ast_pretty::pprust::param_to_string
  10: rustc_ast_pretty::pprust::State::print_type
  11: rustc_ast_pretty::pprust::State::print_type
  12: rustc_ast_pretty::pprust::print_crate
  13: rustc_driver::pretty::print_after_hir_lowering
  14: rustc_driver::pretty::print_after_hir_lowering
  15: <rustc_driver::DEFAULT_HOOK as core::ops::deref::Deref>::deref
  16: <rustc_driver::DEFAULT_HOOK as core::ops::deref::Deref>::deref
  17: rustc_driver::pretty::print_after_hir_lowering
  18: <rustc_driver::DEFAULT_HOOK as core::ops::deref::Deref>::deref
  19: <rustc_span::symbol::SymbolStr as core::fmt::Display>::fmt
  20: rustc_mir::dataflow::impls::borrowed_locals::MaybeBorrowedLocals::all_borrows
  21: std::sys::windows::thread::Thread::new
  22: BaseThreadInitThunk
  23: RtlUserThreadStart
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: rustc 1.46.0-nightly (feb3536eb 2020-06-09) running on x86_64-pc-windows-msvc
note: compiler flags: -Z unstable-options -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type lib
note: some of the compiler flags provided by cargo are hidden
query stack during panic:
end of query stack

>rustup show
Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\JR\.rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-msvc
nightly-x86_64-pc-windows-msvc

installed targets for active toolchain
--------------------------------------

i686-pc-windows-msvc
x86_64-pc-windows-msvc

active toolchain
----------------

stable-x86_64-pc-windows-msvc (default)
rustc 1.44.1 (c7087fe00 2020-06-17)

**Comment by dtolnay** [comment]
This is a crash in rustc and would need to be reported to https://github.com/rust-lang/rust.

Are you able to share the code on which this can be reproduced?

**Comment by JRAndreassen** [comment]
Thanks for getting back to me.
It's kind of deep in layers of code..
I'll see if I can isolate it..
Thanks
  JR

**Comment by dtolnay** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/73626.
