### ISSUE TITLE
`cargo expand` fails with memory allocation errors on Ubuntu 18.04

### ISSUE THREAD

**Issue by picowar** [dtolnay/cargo-expand#87]
I cannot get `cargo expand` to work at all on Ubuntu 18.04. I have replicated this issue in a VM running Ubuntu 18.04 as well. I am using the default example code 
```
#[derive(Debug)]
struct S;

fn main() {
    println!("{:?}", S);
}
``` 
but I have also tried with other code and get the same following result when I run `cargo expand`:

```
vagrant@vagrant:~/prj/src$ cargo expand
    Checking prj v0.1.0 (/home/vagrant/prj)
    Finished check [unoptimized + debuginfo] target(s) in 0.07s

memory allocation of 8391155392347897856 bytes failedAborted (core dumped)
```

The number of bytes doesn't change between computers or between different code. 

I don't necessarily need `$ cargo expand` as `$ cargo rustc --profile=check -- -Zunstable-options --pretty=expanded` works perfectly but figured this was worth investigating.

**Comment by dtolnay** [comment]
Could you try running it in debug mode to see whether it gives a more useful failure?

```console
$ RUST_BACKTRACE=1 cargo run --manifest-path /path/to/cargo-expand/Cargo.toml -- expand
```

**Comment by ehuss** [comment]
I'm able to reproduce this.  Run `cargo update -p bincode` to update from 1.2.1 to 1.3.0 on latest master (0.6.1).   I haven't dug into why, yet.

**Comment by dtolnay** [comment]
Sounds like a bincode regression -- I'll pin to an older version until it gets sorted out.

FYI @ZoeyR

**Comment by piscisaureus** [comment]
> I'm able to reproduce this. Run `cargo update -p bincode` to update from 1.2.1 to 1.3.0 on latest master (0.6.1). I haven't dug into why, yet.

Happening for me (on windows) as well. Upgrading bincode did not solve the problem for me, the error is still the same:

```
memory allocation of 8391155392347897856 bytes failed
```

**Comment by ehuss** [comment]
@dtolnay There's nothing to pin, it's an artifact of `cargo install` automatically picking up the latest versions.

@piscisaureus The problem is that when you run a bare `cargo install` it picks up the latest versions. You actually want to use the older version of bincode (1.2.1).  You can do this with `cargo install cargo-expand --locked`.

So far I see the regression starts with https://github.com/servo/bincode/pull/309.

**Comment by dtolnay** [comment]
> @dtolnay There's nothing to pin, it's an artifact of `cargo install` automatically picking up the latest versions.

234519982e1275d8a21c1048962ffe0a32a4b1cd pins bincode to make cargo use bincode 1.2.1 when installing cargo-expand 0.6.2.

**Comment by piscisaureus** [comment]
> @piscisaureus The problem is that when you run a bare `cargo install` it picks up the latest versions. You actually want to use the older version of bincode (1.2.1). You can do this with `cargo install cargo-expand --locked`.

That did the trick indeed. Thank you so much for the help!

**Comment by dtolnay** [comment]
I filed https://github.com/servo/bincode/issues/335 to follow up on the problem in bincode.

**Comment by ZoeyR** [comment]
Now that bincode has been fixed should the pin be removed?

**Comment by picowar** [comment]
This is unrelated to the issue, but out of curiosity, how does Rust code segfault? I briefly looked at `bincode` and it is all Rust code with no unsafe blocks, implying that a segfault shouldn't have happened.

**Comment by dtolnay** [comment]
Not a segfault (sigsegv), it's a sigabort. The default behavior is abort on OOM.
