### ISSUE TITLE
Support of raw unions

### ISSUE THREAD

**Issue by Yamakaky** [dtolnay/cargo-expand#9]
https://github.com/rust-lang/rust/issues/32836

**Comment by dtolnay** [comment]
There isn't anything in cargo-expand that would need to deal with raw unions. Can you give some more detail about what you are asking? If rustfmt is failing on code containing unions, you need to install a newer version of rustfmt. The newest one definitely supports them.

```
$ cargo install rustfmt --force
```

**Comment by Yamakaky** [comment]
Right, sorry.
