### ISSUE TITLE
error: no such subcommand: `+nightly`

### ISSUE THREAD

**Issue by nmattia** [dtolnay/cargo-expand#92]
The `cargo-expand` executable fails to run (built from master):

```
$ cargo-expand --help
error: no such subcommand: `+nightly`
```

I can work around this by setting `CARGO_EXPAND_NO_RUN_NIGHTLY=true`. It looks like otherwise `cargo-expand` assumes a `rustup`-installed cargo (vanilla cargo doesn't accept `+nightly` I think).

**Comment by dtolnay** [comment]
Could you try whether cargo-expand 1.0.1 is any better?

**Comment by nmattia** [comment]
This works great, thanks for the quick response!
