### ISSUE TITLE
Filter some macros

### ISSUE THREAD

**Issue by hustxiaoc** [dtolnay/cargo-expand#96]
For some macros like log!, trace!  is there a way to filter them?

**Comment by Mingun** [comment]
Even better if you could specify what macros should keep unexpanded. For example, when examining output of the `serde_derive` generated code I would be like to not expand `try!` macro.

**Comment by dtolnay** [comment]
Closing in favor of #68 since these are about effectively equivalent functionality.

**Comment by Mingun** [comment]
@dtolnay , just do not forget about case with `serde_derive`: `try!` macro defined in the `serde_derive` generated code and I'd like to not expand it
