### ISSUE TITLE
Feature request: enable expand single item ({}) in ugly mode.

### ISSUE THREAD

**Issue by xiaoxiangmoe** [dtolnay/cargo-expand#97]
https://github.com/dtolnay/cargo-expand/blob/72c640677c0c9227f6aba11726f2d9d173ee9efa/src/main.rs#L131-L154

Can we enable expand single item in ugly mode? Using rustfmt is too slow for complex macros.

**Comment by dtolnay** [comment]
I added a feature to format with https://github.com/dtolnay/prettyplease instead of rustfmt, which should be about 20&times; faster.

```console
$ cargo install cargo-expand --features prettyplease
```

I'll make this default in a future release.
